### ISSUE TITLE
I can't get it work following the instructions

### ISSUE THREAD

**Issue by jjmarin** [achadwick/styrene#18]
Hi there !

I have followed the instruccions line by line, but I get the following error messages.
I don't know if it is a bug or something I missed or I don't understand.

```
juanj@DESKTOP-JBGUU6I MINGW64 ~/styrene
$ styrene ./gtk3-examples.cfg
INFO: styrene.bundle: Creating tree in ▒C:/Users/juanj/AppData/Local/Temp/styrenetzdbman1/gtk3-examples-w64▒▒
:: Synchronizing package databases...
error: failed to update mingw32 (unexpected system error)
error: failed to update mingw64 (unexpected system error)
error: failed to update msys (unexpected system error)
error: failed to synchronize any databases
error: failed to init transaction (unexpected system error)
INFO: styrene.cmdline: Cleaning up ▒C:/Users/juanj/AppData/Local/Temp/styrenetzdbman1▒
ERROR: styrene.cmdline: Unexpected error while processing ▒./gtk3-examples.cfg▒
Traceback (most recent call last):
  File "C:/msys64/home/juanj/styrene\styrene\cmdline.py", line 260, in main
    process_spec_file(spec, options)
  File "C:/msys64/home/juanj/styrene\styrene\cmdline.py", line 126, in process_spec_file
    written = bundle.write_distributables(tmp_dir, options)
  File "C:/msys64/home/juanj/styrene\styrene\bundle.py", line 189, in write_distributables
    self._init_tree(distroot)
  File "C:/msys64/home/juanj/styrene\styrene\bundle.py", line 416, in _init_tree
    subprocess.check_call(cmd)
  File "C:/msys64/mingw64/lib/python3.6\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pacman', '--sync', '--refresh', '--quiet', '--root', 'C:/Users/juanj/AppData/Local/Temp/styrenetzdbman1/gtk3-examples-w64', '--noprogressbar', '--arch', 'x86_64']' returned non-zero exit status 1.
```

**Comment by jjmarin** [comment]
I'm running Windows 10 Home on a Intel Core i7-6700T with 16GB of RAM

**Comment by achadwick** [comment]
It is failing to initialize MSYS2 tree in the temp dir from the repositories. Please make sure you are online, and maybe try running the command it's trying with a different `--root`?

Immediately before, can you upgrade your normal working MSYS2 installation using the [normal commands](http://www.msys2.org/)?

I'm not sure I like the temp directory it's chosen. Could the paths it uses be too long? Might the filesystem semantics be a bit strange?

Did you try any other options ([see the docs](https://styrene.readthedocs.io/en/latest/cmdline.html#options))?

Consider adding `-o /tmp/test.$$`. Does that fix it?

I can't help much. The error message you're seeing is very unclear.

**Comment by achadwick** [comment]
Sorry, wrong button. Reopened while we're discussing it :smile:

**Comment by achadwick** [comment]
@jjmarin 
Does the `-o` option fix it?

**Comment by jjmarin** [comment]
Hi @achadwick 
It seems that -o /tmp/test.$$ does the trick. It works now !. 

I tried some days ago, without success (I don't remember if I did something wrong)

Thanks

**Comment by chickenkiller** [comment]
I confirm the problem, on a Windows 7 machine. the  `-o` option makes it work.

**Comment by chickenkiller** [comment]
I also noticed that creating `var/lib/pacman/sync` instead of only `var/lib/pacman` goes a bit further, but I get the following issue anyway:

````
:: Synchronizing package databases...
error: failed to update mingw32 (unable to lock database)
error: failed to update mingw64 (unable to lock database)
error: failed to update msys (unable to lock database)
error: failed to synchronize any databases
error: failed to init transaction (unable to lock database)
error: could not lock database: Permission denied
````

**Comment by achadwick** [comment]
Reproduced - sorry for the delay.

I think the only reasonable thing for now is to fix up the quickstart docs so that that they don't give out actively wrong instructions. 

New release shortly, after I figure out why the launchers styrene makes make the individual demos of `gtk3-demo` hang now. Launching cmd.exe and running `mingw64\bin\gtk3-demo.exe` and then launching a demo works fine, so what the heck? 😖
