### ISSUE TITLE
Limit the list of formats associated with a program in the installer

### ISSUE THREAD

**Issue by jjmarin** [achadwick/styrene#19]
I'm trying to build an installer for Evince, the Document Viewer. The installer created using the following .cfg files asks the user to "Select components to install" with a long list of formats that the program could open. I don't know where this list of formats is taken and how can I limit the list of formats. 
$ cat evince.cfg
`[bundle]`
`packages = {pkg_prefix}evince`
`display_name = Evince`
`description = Document viewer for popular multi-page formats`
`launchers = evince.desktop evince-terminal`

`; TODO: expand this. No idea if this correct, just copy-paste from the gedit example`
`delete =`
 `   ; save some major time during configuration`
 `   var/lib/pacman/local/mingw-w64-*-fontconfig-*-*`

`; TODO: expand this`
`nodelete =`

`# The standard "Document Viewer" name only makes sense in GNOME, so`
`# override that.`

`[evince.desktop]`
`name = Evince Document Viewer`

`# Also make a version that runs in the terminal, just to test %F.`

`[evince-terminal]`
`name = Evince Document Viewer (showing terminal output)`
`terminal = True`
`icon = evince`
`exec = evince %F`

**Comment by achadwick** [comment]
Try overriding [mimetype](https://styrene.readthedocs.io/en/latest/bundleconf.html#mimetype) in your launcher block.
